# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "../code", "/puppet_code"
    config.vm.synced_folder "../puppetserver", "/puppet_puppetserver"
    puppet.vm.box = "boxcutter/centos72"
    puppet.vm.hostname = "puppet.example.com"
    puppet.vm.network :private_network, ip: "10.0.20.10"
    puppet.hostmanager.aliases = %w(puppet)
    puppet.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppetserver -y
      sudo rm -rf /etc/puppetlabs/code
      sudo ln -s /puppet_code /etc/puppetlabs/code
      sudo rm -rf /etc/puppetlabs/puppetserver
      sudo ln -s /puppet_puppetserver /etc/puppetlabs/puppetserver
      sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
      echo "*.example.com" >> sudo tee /etc/puppetlabs/puppet/autosign.conf
      sudo /opt/puppetlabs/bin/puppetserver gem install hiera-eyaml
      sudo service puppetserver start
    SHELL
  end

  config.vm.define "puppetagent1" do |puppetagent1|
    puppetagent1.vm.box = "boxcutter/centos72"
    puppetagent1.vm.synced_folder ".", "/vagrant"
    puppetagent1.vm.hostname = "puppetagent1.example.com"
    puppetagent1.vm.network :private_network, ip: "10.0.20.11"
    puppetagent1.hostmanager.aliases = %w(puppet-agent1)
    puppetagent1.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

  config.vm.define "puppetagent2" do |puppetagent2|
    puppetagent2.vm.box = "ARTACK/debian-jessie"
    puppetagent2.vm.hostname = "puppetagent2.example.com"
    puppetagent2.vm.network :private_network, ip: "10.0.20.12"
    puppetagent2.hostmanager.aliases = %w(puppet-agent2)
    puppetagent2.vm.provision "shell", inline: <<-SHELL
      wget https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
      sudo dpkg -i puppetlabs-release-pc1-jessie.deb
      sudo apt-get update
      #sudo apt-get upgrade -y
      sudo apt-get install puppet-agent -y
      sudo /opt/puppetlabs/bin/puppet agent --enable
      sudo service puppet start
    SHELL
  end

  config.vm.define "puppetagent3" do |puppetagent3|
    puppetagent3.vm.box = "devopsguys/Windows2012R2Eval"
    puppetagent3.vm.hostname = "puppetagent3"
    puppetagent3.vm.network :private_network, ip: "10.0.20.13"
    puppetagent3.hostmanager.aliases = %w(puppetagent3)
    puppetagent3.vm.provision "shell", :path => "../code/windows.ps1"
  end
end